# Generated by Django 5.2.4 on 2025-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image for the post', null=True, upload_to='blog_posts/'),
        ),
    ]
