# Generated by Django 5.2.4 on 2025-07-30 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='foodexperience',
            options={'ordering': ['-tried_date']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-taken_date', '-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='secondary_image',
            new_name='hero_image',
        ),
        migrations.RenameField(
            model_name='foodexperience',
            old_name='is_recommended',
            new_name='would_recommend',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='countries_visited',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='dishes_tried',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='main_content',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='years_traveling',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='foodexperience',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='foodexperience',
            name='taste_rating',
        ),
        migrations.RemoveField(
            model_name='foodexperience',
            name='value_rating',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='camera_model',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_featured_in_gallery',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='lens',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='settings',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(default='Welcome to our travel blog!'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='blog.destination'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodexperience',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('food', 'Food'), ('culture', 'Culture'), ('architecture', 'Architecture'), ('people', 'People'), ('nature', 'Nature'), ('street', 'Street'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='foodexperience',
            name='blog_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_experiences', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='foodexperience',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodexperience',
            name='price_range',
            field=models.CharField(choices=[('$', 'Budget'), ('$$', 'Mid-range'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$', max_length=5),
        ),
        migrations.AlterField(
            model_name='foodexperience',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
